# Generated by Django 4.1 on 2024-08-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="post_author",
            new_name="author",
        ),
    ]
